version: "3.8"

services:

  router:
    environment:
      SELF_SIGNED_ONLY: "1"
    ports:
      - "8080:80"
      - "4443:443"

  application:
    volumes:
      - type: bind
        source: ./app/
        target: /scripts/
        consistency: consistent
    env_file: .db.env

  database:
    environment:
      - MYSQL_ROOT_PASSWORD=111
    ports:
      - "3306:3306"

networks:
  hostnet:
    external: false
    driver: bridge
    name: hostnet
  backend:
    internal: false
    driver: bridge
